---
- hosts: healthstats
  become: yes
  gather_facts: false

  tasks:
  - name: Ensure pushgateway folder exists
    file:
      path: $HOME/pushgateway
      state: directory

  - name: Download ARMv7 Pushgateway
    unarchive:
      src: https://github.com/prometheus/pushgateway/releases/download/v0.5.2/pushgateway-0.5.2.linux-armv7.tar.gz
      dest: $HOME/pushgateway
      extra_opts: [--strip-components=1]
      remote_src: yes

  - name: Copy Pushgateway Dockerfile and config file
    copy:
      src: pushgateway/Dockerfile
      dest: $HOME/pushgateway/
      owner: pi
      mode: 0644

  - name: Build Pushgateway docker image
    docker_image:
       path: $HOME/pushgateway
       name: pushgateway-rpi

  - name: Run Pushgateway as a docker container
    docker_container:
      name: pushgateway-rpi
      image: pushgateway-rpi
      published_ports:
        - 9091:9091
      restart_policy: always

  - name: Git clone health stats collector
    git:
      repo: https://github.com/waltzofpearls/healthstats-collector.git
      dest: $HOME/healthstats

  - name: Build health stats docker image
    docker_image:
      path: $HOME/healthstats
      name: healthstats-rpi
      force: yes

  - name: Run health stats as a docker container
    docker_container:
      name: healthstats-rpi
      image: healthstats-rpi
      restart_policy: always
      volumes:
        - /root/.garmin:/root/.garmin
      env:
        PYTHONPATH: /healthstats/Fit
        PUSHGATEWAY: healthstats.rpi.topbass.studio:9091
        JOB_NAME: healthstats
        TIMEZONE: America/Vancouver
        GRAFANA_API: http://grafana.rpi.topbass.studio:3000/api
