- name: Set up reckon
  hosts: reckon
  gather_facts: false

  tasks:
  - name: Download ARMv7 reckon
    unarchive:
      src: https://github.com/waltzofpearls/reckon/releases/download/v0.1.0/reckon_0.1.0_linux_arm.tar.gz
      dest: $HOME
      remote_src: yes

  - name: Delete reckon directory
    file:
      state: absent
      path: $HOME/reckon

  - name: Rename unarchived folder to reckon
    command: mv -Tn $HOME/reckon_0.1.0_linux_arm $HOME/reckon

  - name: Copy reckon Dockerfile
    copy:
      src: "{{ item }}"
      dest: $HOME/reckon/
      owner: pi
      mode: 0644
    with_fileglob:
      - reckon/*

  - name: Build reckon docker image
    docker_image:
      build:
        path: $HOME/reckon
      name: reckon-rpi
      source: build

  - name: Run reckon as a docker container
    docker_container:
      name: reckon-rpi
      image: reckon-rpi
      restart: yes
      ports:
        - "9999:9999"
      restart_policy: always
      env:
        SCHEDULE: "@every 120m"
        TIMEZONE: America/Vancouver
        PROM_EXPORTER_ADDR: :9999
        PROM_CLIENT_URL: http://prometheus.rpi.topbass.studio:9090
        WATCH_LIST: sensehat_temperature,sensehat_humidity
        MODELS: Prophet
        ROLLING_WINDOW: 72h
