{
 "title": "Misty Mountain",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "sensing the environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "raw temperature - today vs yesterday",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "sensehat_temperature", "legendFormat": "temperature" },
    {
     "expr": "sensehat_temperature offset 24h",
     "legendFormat": "temperature @ yesterday"
    }
   ]
  },
  {
   "title": "raw humidity - today vs yesterday",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "sensehat_humidity", "legendFormat": "humidity" },
    { "expr": "sensehat_humidity offset 24h", "legendFormat": "humidity @ yesterday" }
   ]
  },
  {
   "title": "raw pressure - today vs yesterday",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    { "expr": "sensehat_pressure", "legendFormat": "pressure" },
    { "expr": "sensehat_pressure offset 24h", "legendFormat": "pressure @ yesterday" }
   ]
  },
  {
   "title": "more temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "sensehat_temperature", "legendFormat": "temperature @ sensehat" },
    { "expr": "cpu_temperature", "legendFormat": "temperature @ cpu" },
    { "expr": "calibrated_temperature", "legendFormat": "temperature @ calibrated" },
    { "expr": "openweathermap_temperature", "legendFormat": "temperature @ openweathermap" }
   ]
  },
  {
   "title": "more humidities",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "sensehat_humidity", "legendFormat": "humidity @ sensehat" },
    { "expr": "openweathermap_humidity", "legendFormat": "humidity @ openweathermap" }
   ]
  },
  {
   "title": "more pressures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    { "expr": "sensehat_pressure", "legendFormat": "pressure @ sensehat" },
    { "expr": "openweathermap_pressure", "legendFormat": "pressure @ openweathermap" }
   ]
  },
  { "title": "watching the homeland", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "goroutines - prometheus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"prometheus\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "goroutines - node_exporter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\".*node_exporter\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "go threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "free memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "avail disk space in %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/root\"} / node_filesystem_size_bytes{device=\"/dev/root\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "avail disk space in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/root\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}